DROP TABLE IF EXISTS Zone;
CREATE TABLE Zone
(
	ID		VARCHAR(4) NOT NULL,
	state		BOOLEAN,
	PRIMARY KEY (ID),
);

DROP TABLE IF EXISTS Outlet;
CREATE TABLE Outlet
(
	name		VARCHAR(10) NOT NULL,
	onCode		INTEGER(7),
	offCode		INTEGER(7),
	state		BOOLEAN,
	ID		VARCHAR(4),
	PRIMARY KEY (name),
	FOREIGN KEY (ID) REFERENCES Zone(ID),
);

DROP TABLE IF EXISTS Weekly;
CREATE TABLE Weekly
(
	ID		VARCHAR(4) NOT NULL,
	day		CHAR NOT NULL,
	PRIMARY KEY (ID, day),
	FOREIGN KEY (ID) REFERENCES Zone(ID),
);

DROP TABLE IF EXISTS Daily;
CREATE TABLE Daily
(
	ID		VARCHAR(4) NOT NULL,
	day		CHAR NOT NULL,
	enable		BOOLEAN,
	onTimeH		INTEGER(0,2),
	onTimeM		INTEGER(0,2),
	offTimeH	INTEGER(0,2),
	offTimeM	INTEGER(0,2),
	PRIMARY KEY (ID, day),
	FOREIGN KEY (ID) REFERENCES Zone(ID),
	FOREIGN KEY (day) REFERENCES Week(ID),
);
