DROP TABLE IF EXISTS Zone;
CREATE TABLE Zone
(
	ID		INTEGER NOT NULL AUTO_INCREMENT,
	name		VARCHAR(10),
	state		BOOLEAN,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Outlet;
CREATE TABLE Outlet
(
	number		INTEGER NOT NULL AUTO_INCREMENT,
	name		VARCHAR(10),
	state		BOOLEAN,
	onCode		INTEGER(7),
	offCode		INTEGER(7),
	ID		INTEGER NOT NULL,
	PRIMARY KEY (number),
	FOREIGN KEY (ID) REFERENCES Zone(ID)
);

DROP TABLE IF EXISTS Weekly;
CREATE TABLE Weekly
(
	ID		INTEGER NOT NULL,
	day		CHAR NOT NULL,
	PRIMARY KEY (ID, day),
	FOREIGN KEY (ID) REFERENCES Zone(ID)
);

DROP TABLE IF EXISTS Daily;
CREATE TABLE Daily
(
	ID		INTEGER NOT NULL,
	day		CHAR NOT NULL,
	enabled		BOOLEAN,
	onTimeH		INTEGER(2),
	onTimeM		INTEGER(2),
	offTimeH	INTEGER(2),
	offTimeM	INTEGER(2),
	PRIMARY KEY (ID, day),
	FOREIGN KEY (ID, day) REFERENCES Weekly(ID, day)
);
